### ISSUE TITLE
Create examples path

### ISSUE THREAD

**Issue by felipemarts** [DevelBlockchain/bywise#22]
Create a folder with examples of network creation scripts, contract deployment and smart contract standards such as ERC20.
Create at least one example.
Look at test examples in `src/index.ts`, `propagation.test.ts` and `blockchain.test.ts`

**Comment by Jemiiah** [comment]
@felipemarts is this open for contribution would love to work on this I have a good track record on documentation issues here is my onlydust profile : https://app.onlydust.com/u/Jemiiah
