### ISSUE TITLE
Uptade packages

### ISSUE THREAD

**Issue by felipemarts** [DevelBlockchain/bywise#47]
Update deprecated packages from `devel` branch

delete `node_modules` path
delete `package-lock.json`
run `npm install`
run `npm audit` to check for others deprecated packages

**Comment by 0xJeanmi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
I'm full stack developer with experience in languages like PHP, JS, TS and Frameworks like React, Laravel. Also, I made several courses in Alchemy University to be prepared to challenges in web3 like this one. So I hope to move forward in this application.

### How I plan on tackling this issue
Well, its just to follow the instructions in issue descriptions, make a little research in the last version of packages and update them,

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
With over four years of experience in blockchain development, I have worked across multiple blockchain ecosystems. My expertise spans the entire development lifecycle—from project conceptualization and smart contract design to managing on-chain interactions, seamless protocol integration, and implementing strong security practices.

This enables me to handle both on-chain and off-chain infrastructure, ensuring the development of reliable, scalable blockchain applications.

**Comment by diegoTech14** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bywise).

### My background and how it can be leveraged
Hello @felipemarts I'm a software engineer from Costa Rica and Dojo Coding member, I have experience with JavaScript, Node, React and also working with multiple packages, think I could help you with this issue efficiently. You can check my OnlyDust profile: https://app.onlydust.com/u/diegoTech14.

### How I plan on tackling this issue
`1. ` Checking all packages: I will start reviewing all deprecated packages in node_modules
`2.` Updating packages: Then I'll update the packages and make ensure that every dependency is okay
`3.` I will run the project to ensure that everything is okay
`4.` If it's needed I can update any documentation 

Thank you for the consideration sir...

Kind regards,

Diego Duarte Fernández.
